name: Build LaTeX documentation
on: [push]
permissions:
  contents: read 
  pages: write  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: doc
          root_file: discretisation.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: doc/discretisation.pdf

      - name: Deploy PDF file
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          CLEAN: true
          SINGLE_COMMIT: true
          FOLDER: doc
          GIT_CONFIG_NAME: eikehmueller
          GIT_CONFIG_EMAIL: e.mueller@bath.ac.uk